@Library('my-share') _
pipeline {
	agent any
	environment {
		iniFileSvnUrl = "http://1.119.142.186:82/svn/svndate/Test/自动化测试/jenkins/pipeline/ini/base_image"
		iniLocalPath = "${env.WORKSPACE}/ini/base_image.ini"
		//jenkins上SVN账号的ID Jenkins->凭据->系统->全局凭据->
		//找到需要切换的账号，点击更新按钮找到当前用户的ID 替换到这里，就会使用这个账号执行svn操作
		svnUserID = "eb626597-f71f-4a3a-8b09-9871695adcaf"
	}
	tools ('加载工具') {
		jdk 'jdk-1.8'
	}
	parameters {
	  choice choices: ['xmgl','rrl', 'fkw','public'], description: '选择平台名称', name: 'platformName'
	  string defaultValue: '', description: '待构建镜像名称列表(使用英文,分割多个项目,如mysql,resin;具体可选请参照ini文件);为空时构建所有当前平台下的镜像', name: 'imagelist', trim: true
	}
    stages {
		stage('获取ini配置文件'){
			steps {
				script {
					checkout_svn "${env.iniFileSvnUrl}","ini"
				}
			}
		}
		stage('执行镜像构建'){
			steps {
				script {
					build_image.buildBaseImage "${platformName}","${imagelist}"
				}
			}
		}
    }
}