@Library('my-share') _
pipeline {
    agent any
	environment {
		//jenkins上SVN账号的ID Jenkins->凭据->系统->全局凭据->
		//找到需要切换的账号，点击更新按钮找到当前用户的ID 替换到这里，就会使用这个账号执行svn操作
		svnUserID = "eb626597-f71f-4a3a-8b09-9871695adcaf"
	}
	tools ('加载工具') {
		jdk 'jdk-1.8'
	}
	parameters {
	  choice choices: ['rrl', 'fkw', 'jsw', 'fzbd', 'sale', 'xf', 'xfapp', 'pf', 'uc', 'sms', 'rrlys', 'fxshop', 'gw', 'hy', 'ip', 'wexam', 'yun', 'bot'], description: '打包平台', name: 'platformName'
	  string defaultValue: '', description: '待打包项目列表(使用英文,分割多个项目)', name: 'projectlist', trim: true
	  string defaultValue: '', description: '线上打包描述信息', name: 'description', trim: true
	  string defaultValue: '0', description: '项目管理平台调用时使用,测试打包不需要修改此项', name: 'packageId', trim: true
	}
    stages {
		stage('执行打包操作'){
			steps {
				script {
					online_package "${platformName}","${projectlist}","${description}","${packageId}"
				}
			}
		}
    }
}